### PR TITLE
initial CRAN release

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by DominiqueMakowski** [comment]
🎉 

I'll draft an announcement post asap

```
this notification has been generated automatically.
Your package effectsize_0.2.0.tar.gz has been built for Windows and
will be published within 24 hours in the corresponding CRAN directory.
R version 3.6.2 (2019-12-12)
```

**Comment by strengejacke** [comment]
_effectsize_ is not _correlation_?

**Comment by DominiqueMakowski** [comment]
oooops 😅

**Comment by DominiqueMakowski** [comment]
my priors were too strong

**Pull request merged**
