### PR TITLE
[Feature] pseudo-ANOVA method to test if a number of correlations are similar

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
Based on this method by Nick Brown: https://twitter.com/sTeamTraen/status/1571573991667601408

``` r
library(correlation)
r <- correlation(mtcars)
anova(r)
#> Test that the correlations are similar.
#> 
#> Chi2(54) |      p
#> -----------------
#> 984.13   | > .999
```

<sup>Created on 2022-09-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I have no idea if it's meaningful / useful, though 
@mattansb @bwiernik

### CODE REVIEW

**Comment by mattansb** [comment]
It is not here - this assumes the correlations are independent (from different samples), whereas in your example these are from the same sample / share variables between them.

The code from that tweet is an omnibus version of the independent samples idea in #264.

As for the actual code - no idea.

**Comment by DominiqueMakowski** [comment]
Ah right right so this cannot work as a method for easycorrelation since it's always on the same sample

**Comment by bwiernik** [comment]
Here is a function for the covariance among sample correlations, from Nel or Alf & Graf

https://github.com/bwiernik/configural/blob/d60115ac6898e532c526265d12879d591d1f9964/R/utility.R#L128

This could be used to construct ANOVA or contrasts if you thought that would be useful

**Comment by bwiernik** [comment]
ICYMI, what Nick discovered was the classical test for homogeneity used in meta-analysis https://twitter.com/wviechtb/status/1571760357391097857?s=46&t=mE4b89z-WPl7A5p7vzPapQ

**Comment by bwiernik** [comment]
Going to close this for now -- we can revisit within-sample correlation comparisons or applying this method to between-sample correlation comparisons in a future PR

**Pull request closed without merging**
