### PR TITLE
Prepare CRAN submission

### LINKED ISSUE #283: CRAN check failures
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_correlation.html>.

Please correct before 2023-04-10 to safely retain your package on CRAN.

Best,
-k

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #283

### CODE REVIEW

**Comment by bwiernik** [comment]
Let's merge this one before releasing:

https://github.com/easystats/correlation/pull/285

**Comment by strengejacke** [comment]
Yes, I just wanted to open a PR for this. I think you must submit, anyway.

**Comment by bwiernik** [comment]
@IndrajeetPatil I don't understand what these failed tests mean. Could you help me resolve?

**Comment by bwiernik** [comment]
I've got fixes for the warnings in the examples and vignettes. I'm not following why there are errors in oldrel-2 and oldrel-3. The errors don't make sense to me why they would occur there. @IndrajeetPatil any insights?

**Comment by IndrajeetPatil** [comment]
> I've got fixes for the warnings in the examples and vignettes. I'm not following why there are errors in oldrel-2 and oldrel-3. The errors don't make sense to me why they would occur there. @IndrajeetPatil any insights?

I am not sure either why the snapshots don't match for these versions. I had created an issue to track this: https://github.com/easystats/correlation/issues/281

But, this should not get in the way of the CRAN release, since CRAN doesn't test packages on oldrel-2 or prior releases.

**Review by bwiernik — APPROVED** [review]

**Comment by strengejacke** [comment]
Why didn't you submit the build from this branch before merging?

**Comment by bwiernik** [comment]
Oh, the workflow I have used is to merge and then submit from main

**Pull request merged**
